# Generated by Django 4.0.1 on 2022-02-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'style',
            },
        ),
        migrations.AlterField(
            model_name='drawingmodel',
            name='buy_price',
            field=models.IntegerField(default=0),
        ),
    ]
