# Generated by Django 4.0.2 on 2022-02-24 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketmodel',
            old_name='sel_price',
            new_name='sell_price',
        ),
        migrations.AlterField(
            model_name='marketmodel',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketmodel',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
