# Generated by Django 4.0.1 on 2022-02-24 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('drawing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmodel',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketmodel',
            name='drawing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.drawingmodel'),
        ),
        migrations.AddField(
            model_name='marketmodel',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
